# Generated by Django 3.2 on 2023-03-18 14:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '8-xxx-xxx-xx-xx'", regex='^8-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Processed_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected')], max_length=50, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_order', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_order', to='market.order', verbose_name='Заказ')),
            ],
        ),
    ]
