# Generated by Django 3.2 on 2023-03-20 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20230318_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата обработки заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='обработал заказ'),
        ),
    ]
